spring:
  datasource:
    url: jdbc:mysql://10.22.201.117:3307/petshop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: 10.22.201.117
  rabbitmq:
    host: 10.22.201.117
  elasticsearch:
    uris: http://10.22.201.117:9200
